# Generated by Django 4.0.4 on 2022-05-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactgrowgreen',
            name='email',
        ),
        migrations.AddField(
            model_name='contactgrowgreen',
            name='user_email',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
