# Generated by Django 4.0.3 on 2022-04-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantTree',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tree_name', models.CharField(choices=[('N', 'Neem'), ('K', 'Karanja'), ('M', 'Mango'), ('J', 'Jamun'), ('B', 'Banyan'), ('A', 'Amrood'), ('BB', 'Bamboo'), ('BE', 'Ber'), ('NI', 'Nimboo')], max_length=100)),
                ('tree_planted_date', models.DateTimeField(auto_now_add=True)),
                ('tree_pictures', models.ImageField(upload_to='tree_planted_images/ %Y/ %m/ %d/')),
                ('tree_description', models.TextField(default=models.CharField(choices=[('N', 'Neem'), ('K', 'Karanja'), ('M', 'Mango'), ('J', 'Jamun'), ('B', 'Banyan'), ('A', 'Amrood'), ('BB', 'Bamboo'), ('BE', 'Ber'), ('NI', 'Nimboo')], max_length=100))),
                ('tree_planted_rewards', models.BigIntegerField()),
            ],
        ),
    ]
