# Generated by Django 4.0.3 on 2022-04-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantTree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttree',
            name='tree_pictures',
            field=models.ImageField(upload_to='static/tree_planted_images/ %Y/ %m/ %d/'),
        ),
    ]
