# Generated by Django 4.0.4 on 2022-05-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantTree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantatree',
            name='tree_pictures',
            field=models.ImageField(upload_to='tree_planted_images/ %Y/ %m/ %d/'),
        ),
    ]
