# Generated by Django 4.0.4 on 2022-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantTree', '0003_alter_plantatree_tree_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantatree',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='plantatree',
            name='tree_pictures',
            field=models.ImageField(upload_to='static/tree_planted_images/ %Y/ %m/ %d/'),
        ),
    ]
