# Generated by Django 4.0.4 on 2022-06-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantTree', '0004_plantatree_points_alter_plantatree_tree_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantatree',
            name='tree_pictures',
            field=models.ImageField(upload_to='media/treePlantedImages/ %Y/ %m/ %d/'),
        ),
    ]
