# Generated by Django 4.0.4 on 2022-05-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=100)),
                ('slider_title_descripiton', models.CharField(max_length=400)),
                ('slider_images', models.ImageField(upload_to='static/assets/slider_images/ % Y / % m / % d/')),
                ('tree_plantation_map_title', models.CharField(max_length=100)),
                ('tree_plantation_map_image', models.ImageField(upload_to='static/assets/slider_images/ % Y / % m / % d/')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageTrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_name', models.CharField(max_length=50)),
                ('tree_details', models.CharField(max_length=200)),
                ('tree_image', models.ImageField(upload_to='static/assets/homepageTrees/ % Y / % m / % d/')),
            ],
        ),
    ]
